export default {
  'What form of sexual harrassment did you experience?': 'test',
  'When did the incident take place?': 'test',
  'Were there multiple incidents related to the same perpetrator?': 'test',
  'Did the incident take place in the UK?': 'test',
  'What kind of location did the incident take place in?': 'test',
  'Where exactly did the incident take place?': 'test',
  'Was the harrasser(s) or perpetrator(s) a...': 'test',
  'What is their relationship to you?': 'test',
  'Have you experienced sexual harrassment by the same perpetrator before?':
    'test',
  'Have you reported this incident elsewhere?': 'test',
  'Who did you report this incident to?': 'test',
  'Was any action taken?': 'test',
  'Did anything discourage you from reporting?': 'test',
  'What was your employment status at the time of the incident?': 'test',
  'What work were performing at the time of the incident?': 'test',
  'What age were you at the time of the incident': 'test',
  'What is your gender?': 'test',
  'Describe what happened in your own words.': 'test',
  'How satisfied are you with the way your report(s) was handled?': 'test',
  'Is your gender identity the same as that assigned at birth?': 'test',
  'What option best describes your ethinicity?': 'test',
  'Do you identify as a deaf or disabled person?': 'test',
  'Which of the following best describes your sexuality?': 'test',
};
